services:
  - type: web
    name: bmss-backend
    env: docker
    repo: https://github.com/SEU_USUARIO/SEU_REPO
    region: oregon
    plan: free
    dockerContext: ./backend/backend
    dockerfilePath: ./backend/backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
