services:
  - type: web
    name: bmss-backend
    env: docker
    repo: https://github.com/SamuelRNeves/bmss
    region: oregon
    plan: free
    dockerContext: ./backend/backend
    dockerfilePath: ./backend/backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: BMSS_SENTIMENT_BASE_URL
        value: https://bmss-sentiment.onrender.com
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: SPRING_MAIL_FROM
        sync: false
