# ===============================
# 💾 MySQL Local
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3307/bmss_db
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# ☁️ CLOUDINARY (LOCAL - valores fixos)
# ===============================
cloudinary.cloud-name=local-dev
cloudinary.api-key=local-key
cloudinary.api-secret=local-secret

# ===============================
# ✉️ RESEND EMAIL (LOCAL)
# ===============================
resend.api.key=dummy-key-para-teste
resend.from.email=BMSS Alerts <onboarding@resend.dev>

# ===============================
# 🔐 JWT LOCAL
# ===============================
jwt.secret=HERqL52+B7X0SGBrODvJXLZcoAVU3PQVih6S86JCF8DlRsshQTT2ios7bzZu4wONhB3E1B67Vv/PoSoUX+tafQ==

# ===============================
# 📰 API DE NOTÍCIAS
# ===============================
newsapi.apiKey=2397c71979b14eaea433a03179807359

# ===============================
# ⚙️ LOGS E TIMEZONE
# ===============================
spring.jackson.time-zone=America/Sao_Paulo
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# ===============================
# 🌐 SERVER CONFIG (LOCAL)
# ===============================
server.port=8080